name: build-and-test-differential

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  prevent-no-label-execution:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/prevent-no-label-execution.yaml@v1
    with:
      label: tag:run-build-and-test-differential

  check-directory-changes-and-label:
    needs: prevent-no-label-execution
    runs-on: ubuntu-22.04
    outputs:
      changes_detected: ${{ steps.check-changes-and-label.outputs.ok }}
    steps:
      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check for changes in a specific directory and label
        id: check-changes-and-label
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep -q '^autoware_lanelet2_map_validator/'; then
            if  [ "${{ needs.prevent-no-label-execution.outputs.run }}" == 'true' ]; then
              echo "ok=true" >> "$GITHUB_OUTPUT"
            else
              echo "ok=false" >> "$GITHUB_OUTPUT"
              exit 1
            fi
          else
            echo "ok=false" >> "$GITHUB_OUTPUT"
            exit 1
          fi

  build-and-test-differential:
    needs: check-directory-changes
    if: ${{ needs.check-directory-changes.outputs.ok == 'true' }}
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}${{ matrix.container-suffix }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        container-suffix:
          - ""
          - -cuda
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware:latest-prebuilt
            build-depends-repos: build_depends.repos

    steps:
      - name: Check No Label Execution
        run: |
          if [ "${{ needs.prevent-no-label-execution.outputs.run }}" != 'true' ]; then
            echo "tag:run-build-and-test-differential is missing"
            exit 1
          fi

      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Show disk space before the tasks
        run: df -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Build
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Test
        id: test
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Upload coverage to CodeCov
        if: ${{ steps.test.outputs.coverage-report-files != '' }}
        uses: codecov/codecov-action@v3
        with:
          files: ${{ steps.test.outputs.coverage-report-files }}
          fail_ci_if_error: false
          verbose: true
          flags: differential

      - name: Show disk space after the tasks
        run: df -h
