# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

name: github-release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag-name:
        description: The name of the tag to release
        type: string
        required: true

jobs:
  build-and-package:
    runs-on: ubuntu-22.04
    container: ghcr.io/autowarefoundation/autoware:core-devel
    
    outputs:
      release_version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: 'feat/embedded_building'

      - name: Install Utilities
        run: |
          apt-get update
          apt-get install -y zip gnupg

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Build the package in Release mode
        run: |
          source /autoware/install/setup.bash
          colcon build \
            --packages-select autoware_lanelet2_map_validator \
            --symlink-install \
            --cmake-args "-DCMAKE_BUILD_TYPE=Release"

      - name: Get Release Version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            REF_NAME="${{ github.event.inputs.tag-name }}"
          else
            REF_NAME="${{ github.ref_name }}"
          fi
          VERSION=${REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Package artifacts
        id: package
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          ZIP_NAME="autoware_lanelet2_map_validator-${VERSION}-ubuntu-22.04.zip"
          mkdir release_package
          cp build/autoware_lanelet2_map_validator/autoware_lanelet2_map_validator release_package/
          cp build/autoware_lanelet2_map_validator/libautoware_lanelet2_map_validator_lib.so release_package/
          cp -r install/autoware_lanelet2_map_validator/share/autoware_lanelet2_map_validator/config release_package/
          cp -r install/autoware_lanelet2_map_validator/share/autoware_lanelet2_map_validator/map_requirements release_package/
          zip -r $ZIP_NAME release_package 
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Sign the package with GPG
        id: gpg-sign
        run: |
          echo "${{ secrets.TEST_GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --batch --yes --detach-sign --armor --pinentry-mode loopback --passphrase "${{ secrets.TEST_GPG_PASSPHRASE }}" -o ${{ steps.package.outputs.zip_name }}.asc ${{ steps.package.outputs.zip_name }}
          echo "signature_name=${{ steps.package.outputs.zip_name }}.asc" >> $GITHUB_OUTPUT
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: |
            autoware_lanelet2_map_validator-*.zip
            autoware_lanelet2_map_validator-*.zip.asc

  release:
    runs-on: ubuntu-22.04
    needs: build-and-package
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-artifact

      - name: Create Release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ needs.build-and-package.outputs.release_version }}"

          files: autoware_lanelet2_map_validator-*
          
          draft: true
          
          generate_release_notes: true